services:
  sveltekit:
    container_name: terra-prime-sveltekit
    build:
      context: ./site
      dockerfile: dockerfile
    ports:
      - 4174:3000
    env_file:
      - ./site/.env
    depends_on:
      - db

  db:
    container_name: terra-prime-db
    image: mysql/mysql-server:latest
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=testaliceDB
      - MYSQL_USER=yodi
      - MYSQL_PASSWORD=Tester@123
    volumes:
      - './db/scripts:/docker-entrypoint-initdb.d'
  phpnyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8081:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
    stdin_open: true

  tunnel:
    container_name: cloudflared-tunnel
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel --no-autoupdate  run
    environment:
      - TUNNEL_TOKEN=eyJhIjoiMjliYTJlMmJiMmM1NjUwNTJiZGZlZjMwOTczYjY0NmYiLCJ0IjoiN2ZkZGIwODUtOTBkOS00ZjcwLWJhNjQtNzFiODU3ODQxYTM2IiwicyI6Ik1UTmtNelZtTmpNdFpUQmlPQzAwTkdSakxXSXdOalV0TW1Fd01HUmlPV1k1TWpkbCJ9

networks:
  default:
    external:
      name: terra-prime