services:
  sveltekit:
    container_name: testalice-sveltekit
    build:
      context: ./site
      dockerfile: dockerfile
    ports:
      - 4174:3000
    env_file:
      - ./site/.env
    depends_on:
      - db

  db:
    container_name: testalice-db
    image: mysql/mysql-server:latest
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=testaliceDB
      - MYSQL_USER=yodi
      - MYSQL_PASSWORD=Tester@123
    volumes:
      - './db/scripts:/docker-entrypoint-initdb.d'
  phpnyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8081:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
    stdin_open: true
 